---
- name: Handle users
  import_tasks: new_user.yml
  tags: user

- name: Handle ssh
  import_tasks: ssh.yml
  tags: ssh

- name: Handle firewall
  import_tasks: firewall.yml
  tags: firewall

- name: Install Packages
  import_tasks: packages.yml
  tags: packages
